name: Pages-GitHub
on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # - name: Get baseURL
      #   run: |
      #     baseURL=$(cat config.toml | awk '/^baseURL/' | awk '{print $3}' | sed "s|[\'\"]||g" | awk -F '//' '{print $2}' | sed "s|/||")
      #     if [[ $baseURL ]]; then
      #       echo "CNAME=$baseURL" >>$GITHUB_ENV
      #       echo "baseURL is ${{ env.CNAME }}"
      #     else
      #       echo "Check baseURL setting in root config.toml please."
      #       cat config.toml
      #     fi

      # - name: Set CNAME
      #   if: ${{ ! contains(env.CNAME, 'github.io') }}
      #   run: echo ${{ env.CNAME }} >"static/CNAME"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.113.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GAYHUB_TOKEN }} # 该项适用于发布到源码相同repo的情况，不能用于发布到其他repo
          personal_token: ${{ secrets.ACTION_ACCESS_TOKEN }}	# 发布到其他repo需要提供上面生成的personal access token
          publish_dir: ./public	# 注意这里指的是要发布哪个文件夹的内容，而不是指发布到目的仓库的什么位置，hugo默认生成静态网页到public文件夹
          external_repository: ${{ github.actor }}/${{ github.actor }}.github.io	# 发布到哪个repo
          publish_branch: pages-hugo	# 发布到哪个branch
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true # make your publish branch with only the latest commit